"""Add group_type to WordGroup

Revision ID: manual_add_group_type
Revises: None  # This is the initial migration
Create Date: 2025-03-31 17:19:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Added import for sqlmodel


# revision identifiers, used by Alembic.
revision: str = "manual_add_group_type"
down_revision: Union[str, None] = None  # Set to None for initial migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "word_groups",
        sa.Column(
            "group_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("word_groups", "group_type")
    # ### end Alembic commands ###
